; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Tests for SimplifyDemandedBits handling of bitcast instructions.
; Verify that demanded bits analysis can "peek through" bitcasts
; with matching per-element bit widths (e.g. i32<->float).

declare float @llvm.copysign.f32(float, float)
declare <4 x float> @llvm.copysign.v4f32(<4 x float>, <4 x float>)
declare <2 x float> @llvm.copysign.v2f32(<2 x float>, <2 x float>)
declare double @llvm.copysign.f64(double, double)
declare void @use_f32(float)
declare void @use_v4f32(<4 x float>)

; Scalar i32->float: copysign demands only the sign bit (bit 31).
; 'or 42' sets bits 1,3,5 which are NOT demanded, should be eliminated.
define float @demanded_through_bitcast_scalar_or(float %mag, i32 %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_scalar_or(
; CHECK-NEXT:    [[BC:%.*]] = bitcast i32 [[SIGN_INT:%.*]] to float
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.copysign.f32(float [[MAG:%.*]], float [[BC]])
; CHECK-NEXT:    ret float [[R]]
;
  %or = or i32 %sign_int, 42
  %bc = bitcast i32 %or to float
  %r = call float @llvm.copysign.f32(float %mag, float %bc)
  ret float %r
}

; Vector <4 x i32> -> <4 x float>: same as above but with vectors.
define <4 x float> @demanded_through_bitcast_vector_or(<4 x float> %mag, <4 x i32> %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_vector_or(
; CHECK-NEXT:    [[BC:%.*]] = bitcast <4 x i32> [[SIGN_INT:%.*]] to <4 x float>
; CHECK-NEXT:    [[R:%.*]] = call <4 x float> @llvm.copysign.v4f32(<4 x float> [[MAG:%.*]], <4 x float> [[BC]])
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %or = or <4 x i32> %sign_int, splat (i32 42)
  %bc = bitcast <4 x i32> %or to <4 x float>
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %mag, <4 x float> %bc)
  ret <4 x float> %r
}

; Scalar i32->float: 'and' with mask that preserves sign bit plus extra bits.
; The extra non-sign bits in the mask are irrelevant; the 'and' should simplify.
define float @demanded_through_bitcast_scalar_and(float %mag, i32 %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_scalar_and(
; CHECK-NEXT:    [[BC:%.*]] = bitcast i32 [[SIGN_INT:%.*]] to float
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.copysign.f32(float [[MAG:%.*]], float [[BC]])
; CHECK-NEXT:    ret float [[R]]
;
  %and = and i32 %sign_int, -2147483606
  %bc = bitcast i32 %and to float
  %r = call float @llvm.copysign.f32(float %mag, float %bc)
  ret float %r
}

; Multi-use bitcast: the bitcast has another use, so SimplifyMultipleUseDemandedBits
; is invoked instead. The 'or' cannot be simplified in-place due to multi-use.
define float @demanded_through_bitcast_multiuse(float %mag, i32 %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_multiuse(
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SIGN_INT:%.*]], 42
; CHECK-NEXT:    [[BC:%.*]] = bitcast i32 [[OR]] to float
; CHECK-NEXT:    call void @use_f32(float [[BC]])
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.copysign.f32(float [[MAG:%.*]], float [[BC]])
; CHECK-NEXT:    ret float [[R]]
;
  %or = or i32 %sign_int, 42
  %bc = bitcast i32 %or to float
  call void @use_f32(float %bc)
  %r = call float @llvm.copysign.f32(float %mag, float %bc)
  ret float %r
}

; Multi-use bitcast with all demanded bits known: SimplifyMultipleUseDemandedBits
; can fold the specific use to a constant.
define float @demanded_through_bitcast_multiuse_known(float %mag, i32 %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_multiuse_known(
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[SIGN_INT:%.*]], 2147483647
; CHECK-NEXT:    [[BC:%.*]] = bitcast i32 [[AND]] to float
; CHECK-NEXT:    call void @use_f32(float [[BC]])
; CHECK-NEXT:    [[R:%.*]] = call float @llvm.fabs.f32(float [[MAG:%.*]])
; CHECK-NEXT:    ret float [[R]]
;
  %and = and i32 %sign_int, 2147483647
  %bc = bitcast i32 %and to float
  call void @use_f32(float %bc)
  %r = call float @llvm.copysign.f32(float %mag, float %bc)
  ret float %r
}

; Negative test: mismatched scalar widths (i64 -> <2 x float>).
; Per-element sizes differ (64 vs 32), so we should NOT peek through.
define <2 x float> @demanded_no_peek_mismatched_width(<2 x float> %mag, i64 %sign_int) {
; CHECK-LABEL: @demanded_no_peek_mismatched_width(
; CHECK-NEXT:    [[OR:%.*]] = or i64 [[SIGN_INT:%.*]], 42
; CHECK-NEXT:    [[BC:%.*]] = bitcast i64 [[OR]] to <2 x float>
; CHECK-NEXT:    [[R:%.*]] = call <2 x float> @llvm.copysign.v2f32(<2 x float> [[MAG:%.*]], <2 x float> [[BC]])
; CHECK-NEXT:    ret <2 x float> [[R]]
;
  %or = or i64 %sign_int, 42
  %bc = bitcast i64 %or to <2 x float>
  %r = call <2 x float> @llvm.copysign.v2f32(<2 x float> %mag, <2 x float> %bc)
  ret <2 x float> %r
}

; Scalar i64->double: verify 64-bit types work too.
define double @demanded_through_bitcast_i64_to_f64(double %mag, i64 %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_i64_to_f64(
; CHECK-NEXT:    [[BC:%.*]] = bitcast i64 [[SIGN_INT:%.*]] to double
; CHECK-NEXT:    [[R:%.*]] = call double @llvm.copysign.f64(double [[MAG:%.*]], double [[BC]])
; CHECK-NEXT:    ret double [[R]]
;
  %or = or i64 %sign_int, 42
  %bc = bitcast i64 %or to double
  %r = call double @llvm.copysign.f64(double %mag, double %bc)
  ret double %r
}

; Multi-use vector bitcast: both the bitcast and the 'or' have multiple uses.
define <4 x float> @demanded_through_bitcast_vector_multiuse(<4 x float> %mag, <4 x i32> %sign_int) {
; CHECK-LABEL: @demanded_through_bitcast_vector_multiuse(
; CHECK-NEXT:    [[OR:%.*]] = or <4 x i32> [[SIGN_INT:%.*]], splat (i32 42)
; CHECK-NEXT:    [[BC:%.*]] = bitcast <4 x i32> [[OR]] to <4 x float>
; CHECK-NEXT:    call void @use_v4f32(<4 x float> [[BC]])
; CHECK-NEXT:    [[R:%.*]] = call <4 x float> @llvm.copysign.v4f32(<4 x float> [[MAG:%.*]], <4 x float> [[BC]])
; CHECK-NEXT:    ret <4 x float> [[R]]
;
  %or = or <4 x i32> %sign_int, splat (i32 42)
  %bc = bitcast <4 x i32> %or to <4 x float>
  call void @use_v4f32(<4 x float> %bc)
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %mag, <4 x float> %bc)
  ret <4 x float> %r
}
